/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-12")
public class ClientRequest implements org.apache.thrift.TBase<ClientRequest, ClientRequest._Fields>, java.io.Serializable, Cloneable, Comparable<ClientRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ClientRequest");

  private static final org.apache.thrift.protocol.TField REQUEST_PARAMETER_FIELD_DESC = new org.apache.thrift.protocol.TField("requestParameter", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField VIEW_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("viewNumber", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField REQUEST_RESPONSE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("requestResponseCode", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField OUTPUT_FIELD_DESC = new org.apache.thrift.protocol.TField("output", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ClientRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ClientRequestTupleSchemeFactory());
  }

  public RequestParameter requestParameter; // required
  public int viewNumber; // required
  public RequestResponseCode requestResponseCode; // required
  public String output; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REQUEST_PARAMETER((short)1, "requestParameter"),
    VIEW_NUMBER((short)2, "viewNumber"),
    REQUEST_RESPONSE_CODE((short)3, "requestResponseCode"),
    OUTPUT((short)4, "output");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REQUEST_PARAMETER
          return REQUEST_PARAMETER;
        case 2: // VIEW_NUMBER
          return VIEW_NUMBER;
        case 3: // REQUEST_RESPONSE_CODE
          return REQUEST_RESPONSE_CODE;
        case 4: // OUTPUT
          return OUTPUT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VIEWNUMBER_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REQUEST_PARAMETER, new org.apache.thrift.meta_data.FieldMetaData("requestParameter", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "RequestParameter")));
    tmpMap.put(_Fields.VIEW_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("viewNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.REQUEST_RESPONSE_CODE, new org.apache.thrift.meta_data.FieldMetaData("requestResponseCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.ENUM        , "RequestResponseCode")));
    tmpMap.put(_Fields.OUTPUT, new org.apache.thrift.meta_data.FieldMetaData("output", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ClientRequest.class, metaDataMap);
  }

  public ClientRequest() {
  }

  public ClientRequest(
    RequestParameter requestParameter,
    int viewNumber,
    RequestResponseCode requestResponseCode,
    String output)
  {
    this();
    this.requestParameter = requestParameter;
    this.viewNumber = viewNumber;
    setViewNumberIsSet(true);
    this.requestResponseCode = requestResponseCode;
    this.output = output;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ClientRequest(ClientRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetRequestParameter()) {
      this.requestParameter = other.requestParameter;
    }
    this.viewNumber = other.viewNumber;
    if (other.isSetRequestResponseCode()) {
      this.requestResponseCode = other.requestResponseCode;
    }
    if (other.isSetOutput()) {
      this.output = other.output;
    }
  }

  public ClientRequest deepCopy() {
    return new ClientRequest(this);
  }

  @Override
  public void clear() {
    this.requestParameter = null;
    setViewNumberIsSet(false);
    this.viewNumber = 0;
    this.requestResponseCode = null;
    this.output = null;
  }

  public RequestParameter getRequestParameter() {
    return this.requestParameter;
  }

  public ClientRequest setRequestParameter(RequestParameter requestParameter) {
    this.requestParameter = requestParameter;
    return this;
  }

  public void unsetRequestParameter() {
    this.requestParameter = null;
  }

  /** Returns true if field requestParameter is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestParameter() {
    return this.requestParameter != null;
  }

  public void setRequestParameterIsSet(boolean value) {
    if (!value) {
      this.requestParameter = null;
    }
  }

  public int getViewNumber() {
    return this.viewNumber;
  }

  public ClientRequest setViewNumber(int viewNumber) {
    this.viewNumber = viewNumber;
    setViewNumberIsSet(true);
    return this;
  }

  public void unsetViewNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VIEWNUMBER_ISSET_ID);
  }

  /** Returns true if field viewNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetViewNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __VIEWNUMBER_ISSET_ID);
  }

  public void setViewNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VIEWNUMBER_ISSET_ID, value);
  }

  public RequestResponseCode getRequestResponseCode() {
    return this.requestResponseCode;
  }

  public ClientRequest setRequestResponseCode(RequestResponseCode requestResponseCode) {
    this.requestResponseCode = requestResponseCode;
    return this;
  }

  public void unsetRequestResponseCode() {
    this.requestResponseCode = null;
  }

  /** Returns true if field requestResponseCode is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestResponseCode() {
    return this.requestResponseCode != null;
  }

  public void setRequestResponseCodeIsSet(boolean value) {
    if (!value) {
      this.requestResponseCode = null;
    }
  }

  public String getOutput() {
    return this.output;
  }

  public ClientRequest setOutput(String output) {
    this.output = output;
    return this;
  }

  public void unsetOutput() {
    this.output = null;
  }

  /** Returns true if field output is set (has been assigned a value) and false otherwise */
  public boolean isSetOutput() {
    return this.output != null;
  }

  public void setOutputIsSet(boolean value) {
    if (!value) {
      this.output = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REQUEST_PARAMETER:
      if (value == null) {
        unsetRequestParameter();
      } else {
        setRequestParameter((RequestParameter)value);
      }
      break;

    case VIEW_NUMBER:
      if (value == null) {
        unsetViewNumber();
      } else {
        setViewNumber((Integer)value);
      }
      break;

    case REQUEST_RESPONSE_CODE:
      if (value == null) {
        unsetRequestResponseCode();
      } else {
        setRequestResponseCode((RequestResponseCode)value);
      }
      break;

    case OUTPUT:
      if (value == null) {
        unsetOutput();
      } else {
        setOutput((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REQUEST_PARAMETER:
      return getRequestParameter();

    case VIEW_NUMBER:
      return Integer.valueOf(getViewNumber());

    case REQUEST_RESPONSE_CODE:
      return getRequestResponseCode();

    case OUTPUT:
      return getOutput();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REQUEST_PARAMETER:
      return isSetRequestParameter();
    case VIEW_NUMBER:
      return isSetViewNumber();
    case REQUEST_RESPONSE_CODE:
      return isSetRequestResponseCode();
    case OUTPUT:
      return isSetOutput();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ClientRequest)
      return this.equals((ClientRequest)that);
    return false;
  }

  public boolean equals(ClientRequest that) {
    if (that == null)
      return false;

    boolean this_present_requestParameter = true && this.isSetRequestParameter();
    boolean that_present_requestParameter = true && that.isSetRequestParameter();
    if (this_present_requestParameter || that_present_requestParameter) {
      if (!(this_present_requestParameter && that_present_requestParameter))
        return false;
      if (!this.requestParameter.equals(that.requestParameter))
        return false;
    }

    boolean this_present_viewNumber = true;
    boolean that_present_viewNumber = true;
    if (this_present_viewNumber || that_present_viewNumber) {
      if (!(this_present_viewNumber && that_present_viewNumber))
        return false;
      if (this.viewNumber != that.viewNumber)
        return false;
    }

    boolean this_present_requestResponseCode = true && this.isSetRequestResponseCode();
    boolean that_present_requestResponseCode = true && that.isSetRequestResponseCode();
    if (this_present_requestResponseCode || that_present_requestResponseCode) {
      if (!(this_present_requestResponseCode && that_present_requestResponseCode))
        return false;
      if (!this.requestResponseCode.equals(that.requestResponseCode))
        return false;
    }

    boolean this_present_output = true && this.isSetOutput();
    boolean that_present_output = true && that.isSetOutput();
    if (this_present_output || that_present_output) {
      if (!(this_present_output && that_present_output))
        return false;
      if (!this.output.equals(that.output))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_requestParameter = true && (isSetRequestParameter());
    list.add(present_requestParameter);
    if (present_requestParameter)
      list.add(requestParameter);

    boolean present_viewNumber = true;
    list.add(present_viewNumber);
    if (present_viewNumber)
      list.add(viewNumber);

    boolean present_requestResponseCode = true && (isSetRequestResponseCode());
    list.add(present_requestResponseCode);
    if (present_requestResponseCode)
      list.add(requestResponseCode.getValue());

    boolean present_output = true && (isSetOutput());
    list.add(present_output);
    if (present_output)
      list.add(output);

    return list.hashCode();
  }

  @Override
  public int compareTo(ClientRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRequestParameter()).compareTo(other.isSetRequestParameter());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestParameter()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestParameter, other.requestParameter);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetViewNumber()).compareTo(other.isSetViewNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetViewNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewNumber, other.viewNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRequestResponseCode()).compareTo(other.isSetRequestResponseCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestResponseCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestResponseCode, other.requestResponseCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOutput()).compareTo(other.isSetOutput());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutput()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.output, other.output);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ClientRequest(");
    boolean first = true;

    sb.append("requestParameter:");
    if (this.requestParameter == null) {
      sb.append("null");
    } else {
      sb.append(this.requestParameter);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("viewNumber:");
    sb.append(this.viewNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("requestResponseCode:");
    if (this.requestResponseCode == null) {
      sb.append("null");
    } else {
      sb.append(this.requestResponseCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("output:");
    if (this.output == null) {
      sb.append("null");
    } else {
      sb.append(this.output);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ClientRequestStandardSchemeFactory implements SchemeFactory {
    public ClientRequestStandardScheme getScheme() {
      return new ClientRequestStandardScheme();
    }
  }

  private static class ClientRequestStandardScheme extends StandardScheme<ClientRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ClientRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REQUEST_PARAMETER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.requestParameter = new RequestParameter();
              struct.requestParameter.read(iprot);
              struct.setRequestParameterIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VIEW_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.viewNumber = iprot.readI32();
              struct.setViewNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REQUEST_RESPONSE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.requestResponseCode = vr.thrift.RequestResponseCode.findByValue(iprot.readI32());
              struct.setRequestResponseCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OUTPUT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.output = iprot.readString();
              struct.setOutputIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ClientRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.requestParameter != null) {
        oprot.writeFieldBegin(REQUEST_PARAMETER_FIELD_DESC);
        struct.requestParameter.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(VIEW_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.viewNumber);
      oprot.writeFieldEnd();
      if (struct.requestResponseCode != null) {
        oprot.writeFieldBegin(REQUEST_RESPONSE_CODE_FIELD_DESC);
        oprot.writeI32(struct.requestResponseCode.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.output != null) {
        oprot.writeFieldBegin(OUTPUT_FIELD_DESC);
        oprot.writeString(struct.output);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ClientRequestTupleSchemeFactory implements SchemeFactory {
    public ClientRequestTupleScheme getScheme() {
      return new ClientRequestTupleScheme();
    }
  }

  private static class ClientRequestTupleScheme extends TupleScheme<ClientRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ClientRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRequestParameter()) {
        optionals.set(0);
      }
      if (struct.isSetViewNumber()) {
        optionals.set(1);
      }
      if (struct.isSetRequestResponseCode()) {
        optionals.set(2);
      }
      if (struct.isSetOutput()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetRequestParameter()) {
        struct.requestParameter.write(oprot);
      }
      if (struct.isSetViewNumber()) {
        oprot.writeI32(struct.viewNumber);
      }
      if (struct.isSetRequestResponseCode()) {
        oprot.writeI32(struct.requestResponseCode.getValue());
      }
      if (struct.isSetOutput()) {
        oprot.writeString(struct.output);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ClientRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.requestParameter = new RequestParameter();
        struct.requestParameter.read(iprot);
        struct.setRequestParameterIsSet(true);
      }
      if (incoming.get(1)) {
        struct.viewNumber = iprot.readI32();
        struct.setViewNumberIsSet(true);
      }
      if (incoming.get(2)) {
        struct.requestResponseCode = vr.thrift.RequestResponseCode.findByValue(iprot.readI32());
        struct.setRequestResponseCodeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.output = iprot.readString();
        struct.setOutputIsSet(true);
      }
    }
  }

}

