/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-11")
public class PrepareResponse implements org.apache.thrift.TBase<PrepareResponse, PrepareResponse._Fields>, java.io.Serializable, Cloneable, Comparable<PrepareResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PrepareResponse");

  private static final org.apache.thrift.protocol.TField PREPARE_OK_FIELD_DESC = new org.apache.thrift.protocol.TField("prepareOk", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField COMMIT_OK_FIELD_DESC = new org.apache.thrift.protocol.TField("commitOk", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PrepareResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PrepareResponseTupleSchemeFactory());
  }

  public boolean prepareOk; // required
  public boolean commitOk; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PREPARE_OK((short)1, "prepareOk"),
    COMMIT_OK((short)2, "commitOk");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PREPARE_OK
          return PREPARE_OK;
        case 2: // COMMIT_OK
          return COMMIT_OK;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PREPAREOK_ISSET_ID = 0;
  private static final int __COMMITOK_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PREPARE_OK, new org.apache.thrift.meta_data.FieldMetaData("prepareOk", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.COMMIT_OK, new org.apache.thrift.meta_data.FieldMetaData("commitOk", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PrepareResponse.class, metaDataMap);
  }

  public PrepareResponse() {
  }

  public PrepareResponse(
    boolean prepareOk,
    boolean commitOk)
  {
    this();
    this.prepareOk = prepareOk;
    setPrepareOkIsSet(true);
    this.commitOk = commitOk;
    setCommitOkIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PrepareResponse(PrepareResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.prepareOk = other.prepareOk;
    this.commitOk = other.commitOk;
  }

  public PrepareResponse deepCopy() {
    return new PrepareResponse(this);
  }

  @Override
  public void clear() {
    setPrepareOkIsSet(false);
    this.prepareOk = false;
    setCommitOkIsSet(false);
    this.commitOk = false;
  }

  public boolean isPrepareOk() {
    return this.prepareOk;
  }

  public PrepareResponse setPrepareOk(boolean prepareOk) {
    this.prepareOk = prepareOk;
    setPrepareOkIsSet(true);
    return this;
  }

  public void unsetPrepareOk() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PREPAREOK_ISSET_ID);
  }

  /** Returns true if field prepareOk is set (has been assigned a value) and false otherwise */
  public boolean isSetPrepareOk() {
    return EncodingUtils.testBit(__isset_bitfield, __PREPAREOK_ISSET_ID);
  }

  public void setPrepareOkIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PREPAREOK_ISSET_ID, value);
  }

  public boolean isCommitOk() {
    return this.commitOk;
  }

  public PrepareResponse setCommitOk(boolean commitOk) {
    this.commitOk = commitOk;
    setCommitOkIsSet(true);
    return this;
  }

  public void unsetCommitOk() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMMITOK_ISSET_ID);
  }

  /** Returns true if field commitOk is set (has been assigned a value) and false otherwise */
  public boolean isSetCommitOk() {
    return EncodingUtils.testBit(__isset_bitfield, __COMMITOK_ISSET_ID);
  }

  public void setCommitOkIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMMITOK_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PREPARE_OK:
      if (value == null) {
        unsetPrepareOk();
      } else {
        setPrepareOk((Boolean)value);
      }
      break;

    case COMMIT_OK:
      if (value == null) {
        unsetCommitOk();
      } else {
        setCommitOk((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PREPARE_OK:
      return Boolean.valueOf(isPrepareOk());

    case COMMIT_OK:
      return Boolean.valueOf(isCommitOk());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PREPARE_OK:
      return isSetPrepareOk();
    case COMMIT_OK:
      return isSetCommitOk();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PrepareResponse)
      return this.equals((PrepareResponse)that);
    return false;
  }

  public boolean equals(PrepareResponse that) {
    if (that == null)
      return false;

    boolean this_present_prepareOk = true;
    boolean that_present_prepareOk = true;
    if (this_present_prepareOk || that_present_prepareOk) {
      if (!(this_present_prepareOk && that_present_prepareOk))
        return false;
      if (this.prepareOk != that.prepareOk)
        return false;
    }

    boolean this_present_commitOk = true;
    boolean that_present_commitOk = true;
    if (this_present_commitOk || that_present_commitOk) {
      if (!(this_present_commitOk && that_present_commitOk))
        return false;
      if (this.commitOk != that.commitOk)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_prepareOk = true;
    list.add(present_prepareOk);
    if (present_prepareOk)
      list.add(prepareOk);

    boolean present_commitOk = true;
    list.add(present_commitOk);
    if (present_commitOk)
      list.add(commitOk);

    return list.hashCode();
  }

  @Override
  public int compareTo(PrepareResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPrepareOk()).compareTo(other.isSetPrepareOk());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrepareOk()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.prepareOk, other.prepareOk);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCommitOk()).compareTo(other.isSetCommitOk());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommitOk()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commitOk, other.commitOk);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PrepareResponse(");
    boolean first = true;

    sb.append("prepareOk:");
    sb.append(this.prepareOk);
    first = false;
    if (!first) sb.append(", ");
    sb.append("commitOk:");
    sb.append(this.commitOk);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PrepareResponseStandardSchemeFactory implements SchemeFactory {
    public PrepareResponseStandardScheme getScheme() {
      return new PrepareResponseStandardScheme();
    }
  }

  private static class PrepareResponseStandardScheme extends StandardScheme<PrepareResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PrepareResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PREPARE_OK
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.prepareOk = iprot.readBool();
              struct.setPrepareOkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COMMIT_OK
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.commitOk = iprot.readBool();
              struct.setCommitOkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PrepareResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PREPARE_OK_FIELD_DESC);
      oprot.writeBool(struct.prepareOk);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(COMMIT_OK_FIELD_DESC);
      oprot.writeBool(struct.commitOk);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PrepareResponseTupleSchemeFactory implements SchemeFactory {
    public PrepareResponseTupleScheme getScheme() {
      return new PrepareResponseTupleScheme();
    }
  }

  private static class PrepareResponseTupleScheme extends TupleScheme<PrepareResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PrepareResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPrepareOk()) {
        optionals.set(0);
      }
      if (struct.isSetCommitOk()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPrepareOk()) {
        oprot.writeBool(struct.prepareOk);
      }
      if (struct.isSetCommitOk()) {
        oprot.writeBool(struct.commitOk);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PrepareResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.prepareOk = iprot.readBool();
        struct.setPrepareOkIsSet(true);
      }
      if (incoming.get(1)) {
        struct.commitOk = iprot.readBool();
        struct.setCommitOkIsSet(true);
      }
    }
  }

}

