/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-12")
public class RecoveryParameter implements org.apache.thrift.TBase<RecoveryParameter, RecoveryParameter._Fields>, java.io.Serializable, Cloneable, Comparable<RecoveryParameter> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RecoveryParameter");

  private static final org.apache.thrift.protocol.TField REPLICA_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("replicaNumber", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NONCE_FIELD_DESC = new org.apache.thrift.protocol.TField("nonce", org.apache.thrift.protocol.TType.BYTE, (short)2);
  private static final org.apache.thrift.protocol.TField RETRY_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("retryCount", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RecoveryParameterStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RecoveryParameterTupleSchemeFactory());
  }

  public int replicaNumber; // required
  public byte nonce; // required
  public int retryCount; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REPLICA_NUMBER((short)1, "replicaNumber"),
    NONCE((short)2, "nonce"),
    RETRY_COUNT((short)3, "retryCount");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REPLICA_NUMBER
          return REPLICA_NUMBER;
        case 2: // NONCE
          return NONCE;
        case 3: // RETRY_COUNT
          return RETRY_COUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REPLICANUMBER_ISSET_ID = 0;
  private static final int __NONCE_ISSET_ID = 1;
  private static final int __RETRYCOUNT_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REPLICA_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("replicaNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.NONCE, new org.apache.thrift.meta_data.FieldMetaData("nonce", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.RETRY_COUNT, new org.apache.thrift.meta_data.FieldMetaData("retryCount", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RecoveryParameter.class, metaDataMap);
  }

  public RecoveryParameter() {
    this.retryCount = 0;

  }

  public RecoveryParameter(
    int replicaNumber,
    byte nonce,
    int retryCount)
  {
    this();
    this.replicaNumber = replicaNumber;
    setReplicaNumberIsSet(true);
    this.nonce = nonce;
    setNonceIsSet(true);
    this.retryCount = retryCount;
    setRetryCountIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RecoveryParameter(RecoveryParameter other) {
    __isset_bitfield = other.__isset_bitfield;
    this.replicaNumber = other.replicaNumber;
    this.nonce = other.nonce;
    this.retryCount = other.retryCount;
  }

  public RecoveryParameter deepCopy() {
    return new RecoveryParameter(this);
  }

  @Override
  public void clear() {
    setReplicaNumberIsSet(false);
    this.replicaNumber = 0;
    setNonceIsSet(false);
    this.nonce = 0;
    this.retryCount = 0;

  }

  public int getReplicaNumber() {
    return this.replicaNumber;
  }

  public RecoveryParameter setReplicaNumber(int replicaNumber) {
    this.replicaNumber = replicaNumber;
    setReplicaNumberIsSet(true);
    return this;
  }

  public void unsetReplicaNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REPLICANUMBER_ISSET_ID);
  }

  /** Returns true if field replicaNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetReplicaNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __REPLICANUMBER_ISSET_ID);
  }

  public void setReplicaNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REPLICANUMBER_ISSET_ID, value);
  }

  public byte getNonce() {
    return this.nonce;
  }

  public RecoveryParameter setNonce(byte nonce) {
    this.nonce = nonce;
    setNonceIsSet(true);
    return this;
  }

  public void unsetNonce() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NONCE_ISSET_ID);
  }

  /** Returns true if field nonce is set (has been assigned a value) and false otherwise */
  public boolean isSetNonce() {
    return EncodingUtils.testBit(__isset_bitfield, __NONCE_ISSET_ID);
  }

  public void setNonceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NONCE_ISSET_ID, value);
  }

  public int getRetryCount() {
    return this.retryCount;
  }

  public RecoveryParameter setRetryCount(int retryCount) {
    this.retryCount = retryCount;
    setRetryCountIsSet(true);
    return this;
  }

  public void unsetRetryCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RETRYCOUNT_ISSET_ID);
  }

  /** Returns true if field retryCount is set (has been assigned a value) and false otherwise */
  public boolean isSetRetryCount() {
    return EncodingUtils.testBit(__isset_bitfield, __RETRYCOUNT_ISSET_ID);
  }

  public void setRetryCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RETRYCOUNT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REPLICA_NUMBER:
      if (value == null) {
        unsetReplicaNumber();
      } else {
        setReplicaNumber((Integer)value);
      }
      break;

    case NONCE:
      if (value == null) {
        unsetNonce();
      } else {
        setNonce((Byte)value);
      }
      break;

    case RETRY_COUNT:
      if (value == null) {
        unsetRetryCount();
      } else {
        setRetryCount((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REPLICA_NUMBER:
      return Integer.valueOf(getReplicaNumber());

    case NONCE:
      return Byte.valueOf(getNonce());

    case RETRY_COUNT:
      return Integer.valueOf(getRetryCount());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REPLICA_NUMBER:
      return isSetReplicaNumber();
    case NONCE:
      return isSetNonce();
    case RETRY_COUNT:
      return isSetRetryCount();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RecoveryParameter)
      return this.equals((RecoveryParameter)that);
    return false;
  }

  public boolean equals(RecoveryParameter that) {
    if (that == null)
      return false;

    boolean this_present_replicaNumber = true;
    boolean that_present_replicaNumber = true;
    if (this_present_replicaNumber || that_present_replicaNumber) {
      if (!(this_present_replicaNumber && that_present_replicaNumber))
        return false;
      if (this.replicaNumber != that.replicaNumber)
        return false;
    }

    boolean this_present_nonce = true;
    boolean that_present_nonce = true;
    if (this_present_nonce || that_present_nonce) {
      if (!(this_present_nonce && that_present_nonce))
        return false;
      if (this.nonce != that.nonce)
        return false;
    }

    boolean this_present_retryCount = true;
    boolean that_present_retryCount = true;
    if (this_present_retryCount || that_present_retryCount) {
      if (!(this_present_retryCount && that_present_retryCount))
        return false;
      if (this.retryCount != that.retryCount)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_replicaNumber = true;
    list.add(present_replicaNumber);
    if (present_replicaNumber)
      list.add(replicaNumber);

    boolean present_nonce = true;
    list.add(present_nonce);
    if (present_nonce)
      list.add(nonce);

    boolean present_retryCount = true;
    list.add(present_retryCount);
    if (present_retryCount)
      list.add(retryCount);

    return list.hashCode();
  }

  @Override
  public int compareTo(RecoveryParameter other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetReplicaNumber()).compareTo(other.isSetReplicaNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReplicaNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.replicaNumber, other.replicaNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNonce()).compareTo(other.isSetNonce());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNonce()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nonce, other.nonce);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRetryCount()).compareTo(other.isSetRetryCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetryCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retryCount, other.retryCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RecoveryParameter(");
    boolean first = true;

    sb.append("replicaNumber:");
    sb.append(this.replicaNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nonce:");
    sb.append(this.nonce);
    first = false;
    if (!first) sb.append(", ");
    sb.append("retryCount:");
    sb.append(this.retryCount);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecoveryParameterStandardSchemeFactory implements SchemeFactory {
    public RecoveryParameterStandardScheme getScheme() {
      return new RecoveryParameterStandardScheme();
    }
  }

  private static class RecoveryParameterStandardScheme extends StandardScheme<RecoveryParameter> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RecoveryParameter struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REPLICA_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.replicaNumber = iprot.readI32();
              struct.setReplicaNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NONCE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.nonce = iprot.readByte();
              struct.setNonceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RETRY_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.retryCount = iprot.readI32();
              struct.setRetryCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RecoveryParameter struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(REPLICA_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.replicaNumber);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NONCE_FIELD_DESC);
      oprot.writeByte(struct.nonce);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RETRY_COUNT_FIELD_DESC);
      oprot.writeI32(struct.retryCount);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RecoveryParameterTupleSchemeFactory implements SchemeFactory {
    public RecoveryParameterTupleScheme getScheme() {
      return new RecoveryParameterTupleScheme();
    }
  }

  private static class RecoveryParameterTupleScheme extends TupleScheme<RecoveryParameter> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecoveryParameter struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetReplicaNumber()) {
        optionals.set(0);
      }
      if (struct.isSetNonce()) {
        optionals.set(1);
      }
      if (struct.isSetRetryCount()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetReplicaNumber()) {
        oprot.writeI32(struct.replicaNumber);
      }
      if (struct.isSetNonce()) {
        oprot.writeByte(struct.nonce);
      }
      if (struct.isSetRetryCount()) {
        oprot.writeI32(struct.retryCount);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecoveryParameter struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.replicaNumber = iprot.readI32();
        struct.setReplicaNumberIsSet(true);
      }
      if (incoming.get(1)) {
        struct.nonce = iprot.readByte();
        struct.setNonceIsSet(true);
      }
      if (incoming.get(2)) {
        struct.retryCount = iprot.readI32();
        struct.setRetryCountIsSet(true);
      }
    }
  }

}

