/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-12")
public class RecoveryResponse implements org.apache.thrift.TBase<RecoveryResponse, RecoveryResponse._Fields>, java.io.Serializable, Cloneable, Comparable<RecoveryResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RecoveryResponse");

  private static final org.apache.thrift.protocol.TField VIEW_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("viewNumber", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField LOGS_FIELD_DESC = new org.apache.thrift.protocol.TField("logs", org.apache.thrift.protocol.TType.MAP, (short)2);
  private static final org.apache.thrift.protocol.TField NONCE_FIELD_DESC = new org.apache.thrift.protocol.TField("nonce", org.apache.thrift.protocol.TType.BYTE, (short)3);
  private static final org.apache.thrift.protocol.TField CHECK_POINT_FIELD_DESC = new org.apache.thrift.protocol.TField("checkPoint", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField OP_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("opNumber", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField COMMIT_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("commitNumber", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField REPLICA_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("replicaNumber", org.apache.thrift.protocol.TType.I32, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RecoveryResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RecoveryResponseTupleSchemeFactory());
  }

  public int viewNumber; // required
  public Map<Integer,Log> logs; // required
  public byte nonce; // required
  public int checkPoint; // required
  public int opNumber; // required
  public int commitNumber; // required
  public int replicaNumber; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VIEW_NUMBER((short)1, "viewNumber"),
    LOGS((short)2, "logs"),
    NONCE((short)3, "nonce"),
    CHECK_POINT((short)4, "checkPoint"),
    OP_NUMBER((short)5, "opNumber"),
    COMMIT_NUMBER((short)6, "commitNumber"),
    REPLICA_NUMBER((short)7, "replicaNumber");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VIEW_NUMBER
          return VIEW_NUMBER;
        case 2: // LOGS
          return LOGS;
        case 3: // NONCE
          return NONCE;
        case 4: // CHECK_POINT
          return CHECK_POINT;
        case 5: // OP_NUMBER
          return OP_NUMBER;
        case 6: // COMMIT_NUMBER
          return COMMIT_NUMBER;
        case 7: // REPLICA_NUMBER
          return REPLICA_NUMBER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VIEWNUMBER_ISSET_ID = 0;
  private static final int __NONCE_ISSET_ID = 1;
  private static final int __CHECKPOINT_ISSET_ID = 2;
  private static final int __OPNUMBER_ISSET_ID = 3;
  private static final int __COMMITNUMBER_ISSET_ID = 4;
  private static final int __REPLICANUMBER_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VIEW_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("viewNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.LOGS, new org.apache.thrift.meta_data.FieldMetaData("logs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32            , "int"), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Log.class))));
    tmpMap.put(_Fields.NONCE, new org.apache.thrift.meta_data.FieldMetaData("nonce", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.CHECK_POINT, new org.apache.thrift.meta_data.FieldMetaData("checkPoint", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.OP_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("opNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.COMMIT_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("commitNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    tmpMap.put(_Fields.REPLICA_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("replicaNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RecoveryResponse.class, metaDataMap);
  }

  public RecoveryResponse() {
  }

  public RecoveryResponse(
    int viewNumber,
    Map<Integer,Log> logs,
    byte nonce,
    int checkPoint,
    int opNumber,
    int commitNumber,
    int replicaNumber)
  {
    this();
    this.viewNumber = viewNumber;
    setViewNumberIsSet(true);
    this.logs = logs;
    this.nonce = nonce;
    setNonceIsSet(true);
    this.checkPoint = checkPoint;
    setCheckPointIsSet(true);
    this.opNumber = opNumber;
    setOpNumberIsSet(true);
    this.commitNumber = commitNumber;
    setCommitNumberIsSet(true);
    this.replicaNumber = replicaNumber;
    setReplicaNumberIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RecoveryResponse(RecoveryResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.viewNumber = other.viewNumber;
    if (other.isSetLogs()) {
      Map<Integer,Log> __this__logs = new HashMap<Integer,Log>(other.logs.size());
      for (Map.Entry<Integer, Log> other_element : other.logs.entrySet()) {

        Integer other_element_key = other_element.getKey();
        Log other_element_value = other_element.getValue();

        Integer __this__logs_copy_key = other_element_key;

        Log __this__logs_copy_value = new Log(other_element_value);

        __this__logs.put(__this__logs_copy_key, __this__logs_copy_value);
      }
      this.logs = __this__logs;
    }
    this.nonce = other.nonce;
    this.checkPoint = other.checkPoint;
    this.opNumber = other.opNumber;
    this.commitNumber = other.commitNumber;
    this.replicaNumber = other.replicaNumber;
  }

  public RecoveryResponse deepCopy() {
    return new RecoveryResponse(this);
  }

  @Override
  public void clear() {
    setViewNumberIsSet(false);
    this.viewNumber = 0;
    this.logs = null;
    setNonceIsSet(false);
    this.nonce = 0;
    setCheckPointIsSet(false);
    this.checkPoint = 0;
    setOpNumberIsSet(false);
    this.opNumber = 0;
    setCommitNumberIsSet(false);
    this.commitNumber = 0;
    setReplicaNumberIsSet(false);
    this.replicaNumber = 0;
  }

  public int getViewNumber() {
    return this.viewNumber;
  }

  public RecoveryResponse setViewNumber(int viewNumber) {
    this.viewNumber = viewNumber;
    setViewNumberIsSet(true);
    return this;
  }

  public void unsetViewNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __VIEWNUMBER_ISSET_ID);
  }

  /** Returns true if field viewNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetViewNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __VIEWNUMBER_ISSET_ID);
  }

  public void setViewNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __VIEWNUMBER_ISSET_ID, value);
  }

  public int getLogsSize() {
    return (this.logs == null) ? 0 : this.logs.size();
  }

  public void putToLogs(int key, Log val) {
    if (this.logs == null) {
      this.logs = new HashMap<Integer,Log>();
    }
    this.logs.put(key, val);
  }

  public Map<Integer,Log> getLogs() {
    return this.logs;
  }

  public RecoveryResponse setLogs(Map<Integer,Log> logs) {
    this.logs = logs;
    return this;
  }

  public void unsetLogs() {
    this.logs = null;
  }

  /** Returns true if field logs is set (has been assigned a value) and false otherwise */
  public boolean isSetLogs() {
    return this.logs != null;
  }

  public void setLogsIsSet(boolean value) {
    if (!value) {
      this.logs = null;
    }
  }

  public byte getNonce() {
    return this.nonce;
  }

  public RecoveryResponse setNonce(byte nonce) {
    this.nonce = nonce;
    setNonceIsSet(true);
    return this;
  }

  public void unsetNonce() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NONCE_ISSET_ID);
  }

  /** Returns true if field nonce is set (has been assigned a value) and false otherwise */
  public boolean isSetNonce() {
    return EncodingUtils.testBit(__isset_bitfield, __NONCE_ISSET_ID);
  }

  public void setNonceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NONCE_ISSET_ID, value);
  }

  public int getCheckPoint() {
    return this.checkPoint;
  }

  public RecoveryResponse setCheckPoint(int checkPoint) {
    this.checkPoint = checkPoint;
    setCheckPointIsSet(true);
    return this;
  }

  public void unsetCheckPoint() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CHECKPOINT_ISSET_ID);
  }

  /** Returns true if field checkPoint is set (has been assigned a value) and false otherwise */
  public boolean isSetCheckPoint() {
    return EncodingUtils.testBit(__isset_bitfield, __CHECKPOINT_ISSET_ID);
  }

  public void setCheckPointIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CHECKPOINT_ISSET_ID, value);
  }

  public int getOpNumber() {
    return this.opNumber;
  }

  public RecoveryResponse setOpNumber(int opNumber) {
    this.opNumber = opNumber;
    setOpNumberIsSet(true);
    return this;
  }

  public void unsetOpNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPNUMBER_ISSET_ID);
  }

  /** Returns true if field opNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetOpNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __OPNUMBER_ISSET_ID);
  }

  public void setOpNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPNUMBER_ISSET_ID, value);
  }

  public int getCommitNumber() {
    return this.commitNumber;
  }

  public RecoveryResponse setCommitNumber(int commitNumber) {
    this.commitNumber = commitNumber;
    setCommitNumberIsSet(true);
    return this;
  }

  public void unsetCommitNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __COMMITNUMBER_ISSET_ID);
  }

  /** Returns true if field commitNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetCommitNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __COMMITNUMBER_ISSET_ID);
  }

  public void setCommitNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __COMMITNUMBER_ISSET_ID, value);
  }

  public int getReplicaNumber() {
    return this.replicaNumber;
  }

  public RecoveryResponse setReplicaNumber(int replicaNumber) {
    this.replicaNumber = replicaNumber;
    setReplicaNumberIsSet(true);
    return this;
  }

  public void unsetReplicaNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REPLICANUMBER_ISSET_ID);
  }

  /** Returns true if field replicaNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetReplicaNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __REPLICANUMBER_ISSET_ID);
  }

  public void setReplicaNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REPLICANUMBER_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case VIEW_NUMBER:
      if (value == null) {
        unsetViewNumber();
      } else {
        setViewNumber((Integer)value);
      }
      break;

    case LOGS:
      if (value == null) {
        unsetLogs();
      } else {
        setLogs((Map<Integer,Log>)value);
      }
      break;

    case NONCE:
      if (value == null) {
        unsetNonce();
      } else {
        setNonce((Byte)value);
      }
      break;

    case CHECK_POINT:
      if (value == null) {
        unsetCheckPoint();
      } else {
        setCheckPoint((Integer)value);
      }
      break;

    case OP_NUMBER:
      if (value == null) {
        unsetOpNumber();
      } else {
        setOpNumber((Integer)value);
      }
      break;

    case COMMIT_NUMBER:
      if (value == null) {
        unsetCommitNumber();
      } else {
        setCommitNumber((Integer)value);
      }
      break;

    case REPLICA_NUMBER:
      if (value == null) {
        unsetReplicaNumber();
      } else {
        setReplicaNumber((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case VIEW_NUMBER:
      return Integer.valueOf(getViewNumber());

    case LOGS:
      return getLogs();

    case NONCE:
      return Byte.valueOf(getNonce());

    case CHECK_POINT:
      return Integer.valueOf(getCheckPoint());

    case OP_NUMBER:
      return Integer.valueOf(getOpNumber());

    case COMMIT_NUMBER:
      return Integer.valueOf(getCommitNumber());

    case REPLICA_NUMBER:
      return Integer.valueOf(getReplicaNumber());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case VIEW_NUMBER:
      return isSetViewNumber();
    case LOGS:
      return isSetLogs();
    case NONCE:
      return isSetNonce();
    case CHECK_POINT:
      return isSetCheckPoint();
    case OP_NUMBER:
      return isSetOpNumber();
    case COMMIT_NUMBER:
      return isSetCommitNumber();
    case REPLICA_NUMBER:
      return isSetReplicaNumber();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RecoveryResponse)
      return this.equals((RecoveryResponse)that);
    return false;
  }

  public boolean equals(RecoveryResponse that) {
    if (that == null)
      return false;

    boolean this_present_viewNumber = true;
    boolean that_present_viewNumber = true;
    if (this_present_viewNumber || that_present_viewNumber) {
      if (!(this_present_viewNumber && that_present_viewNumber))
        return false;
      if (this.viewNumber != that.viewNumber)
        return false;
    }

    boolean this_present_logs = true && this.isSetLogs();
    boolean that_present_logs = true && that.isSetLogs();
    if (this_present_logs || that_present_logs) {
      if (!(this_present_logs && that_present_logs))
        return false;
      if (!this.logs.equals(that.logs))
        return false;
    }

    boolean this_present_nonce = true;
    boolean that_present_nonce = true;
    if (this_present_nonce || that_present_nonce) {
      if (!(this_present_nonce && that_present_nonce))
        return false;
      if (this.nonce != that.nonce)
        return false;
    }

    boolean this_present_checkPoint = true;
    boolean that_present_checkPoint = true;
    if (this_present_checkPoint || that_present_checkPoint) {
      if (!(this_present_checkPoint && that_present_checkPoint))
        return false;
      if (this.checkPoint != that.checkPoint)
        return false;
    }

    boolean this_present_opNumber = true;
    boolean that_present_opNumber = true;
    if (this_present_opNumber || that_present_opNumber) {
      if (!(this_present_opNumber && that_present_opNumber))
        return false;
      if (this.opNumber != that.opNumber)
        return false;
    }

    boolean this_present_commitNumber = true;
    boolean that_present_commitNumber = true;
    if (this_present_commitNumber || that_present_commitNumber) {
      if (!(this_present_commitNumber && that_present_commitNumber))
        return false;
      if (this.commitNumber != that.commitNumber)
        return false;
    }

    boolean this_present_replicaNumber = true;
    boolean that_present_replicaNumber = true;
    if (this_present_replicaNumber || that_present_replicaNumber) {
      if (!(this_present_replicaNumber && that_present_replicaNumber))
        return false;
      if (this.replicaNumber != that.replicaNumber)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_viewNumber = true;
    list.add(present_viewNumber);
    if (present_viewNumber)
      list.add(viewNumber);

    boolean present_logs = true && (isSetLogs());
    list.add(present_logs);
    if (present_logs)
      list.add(logs);

    boolean present_nonce = true;
    list.add(present_nonce);
    if (present_nonce)
      list.add(nonce);

    boolean present_checkPoint = true;
    list.add(present_checkPoint);
    if (present_checkPoint)
      list.add(checkPoint);

    boolean present_opNumber = true;
    list.add(present_opNumber);
    if (present_opNumber)
      list.add(opNumber);

    boolean present_commitNumber = true;
    list.add(present_commitNumber);
    if (present_commitNumber)
      list.add(commitNumber);

    boolean present_replicaNumber = true;
    list.add(present_replicaNumber);
    if (present_replicaNumber)
      list.add(replicaNumber);

    return list.hashCode();
  }

  @Override
  public int compareTo(RecoveryResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetViewNumber()).compareTo(other.isSetViewNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetViewNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.viewNumber, other.viewNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLogs()).compareTo(other.isSetLogs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logs, other.logs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNonce()).compareTo(other.isSetNonce());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNonce()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nonce, other.nonce);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCheckPoint()).compareTo(other.isSetCheckPoint());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCheckPoint()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.checkPoint, other.checkPoint);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpNumber()).compareTo(other.isSetOpNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.opNumber, other.opNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCommitNumber()).compareTo(other.isSetCommitNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCommitNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.commitNumber, other.commitNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReplicaNumber()).compareTo(other.isSetReplicaNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReplicaNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.replicaNumber, other.replicaNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RecoveryResponse(");
    boolean first = true;

    sb.append("viewNumber:");
    sb.append(this.viewNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("logs:");
    if (this.logs == null) {
      sb.append("null");
    } else {
      sb.append(this.logs);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nonce:");
    sb.append(this.nonce);
    first = false;
    if (!first) sb.append(", ");
    sb.append("checkPoint:");
    sb.append(this.checkPoint);
    first = false;
    if (!first) sb.append(", ");
    sb.append("opNumber:");
    sb.append(this.opNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("commitNumber:");
    sb.append(this.commitNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("replicaNumber:");
    sb.append(this.replicaNumber);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecoveryResponseStandardSchemeFactory implements SchemeFactory {
    public RecoveryResponseStandardScheme getScheme() {
      return new RecoveryResponseStandardScheme();
    }
  }

  private static class RecoveryResponseStandardScheme extends StandardScheme<RecoveryResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RecoveryResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VIEW_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.viewNumber = iprot.readI32();
              struct.setViewNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LOGS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map28 = iprot.readMapBegin();
                struct.logs = new HashMap<Integer,Log>(2*_map28.size);
                int _key29;
                Log _val30;
                for (int _i31 = 0; _i31 < _map28.size; ++_i31)
                {
                  _key29 = iprot.readI32();
                  _val30 = new Log();
                  _val30.read(iprot);
                  struct.logs.put(_key29, _val30);
                }
                iprot.readMapEnd();
              }
              struct.setLogsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NONCE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.nonce = iprot.readByte();
              struct.setNonceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CHECK_POINT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.checkPoint = iprot.readI32();
              struct.setCheckPointIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // OP_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.opNumber = iprot.readI32();
              struct.setOpNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // COMMIT_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.commitNumber = iprot.readI32();
              struct.setCommitNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // REPLICA_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.replicaNumber = iprot.readI32();
              struct.setReplicaNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RecoveryResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(VIEW_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.viewNumber);
      oprot.writeFieldEnd();
      if (struct.logs != null) {
        oprot.writeFieldBegin(LOGS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, struct.logs.size()));
          for (Map.Entry<Integer, Log> _iter32 : struct.logs.entrySet())
          {
            oprot.writeI32(_iter32.getKey());
            _iter32.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NONCE_FIELD_DESC);
      oprot.writeByte(struct.nonce);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CHECK_POINT_FIELD_DESC);
      oprot.writeI32(struct.checkPoint);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(OP_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.opNumber);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(COMMIT_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.commitNumber);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(REPLICA_NUMBER_FIELD_DESC);
      oprot.writeI32(struct.replicaNumber);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RecoveryResponseTupleSchemeFactory implements SchemeFactory {
    public RecoveryResponseTupleScheme getScheme() {
      return new RecoveryResponseTupleScheme();
    }
  }

  private static class RecoveryResponseTupleScheme extends TupleScheme<RecoveryResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecoveryResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetViewNumber()) {
        optionals.set(0);
      }
      if (struct.isSetLogs()) {
        optionals.set(1);
      }
      if (struct.isSetNonce()) {
        optionals.set(2);
      }
      if (struct.isSetCheckPoint()) {
        optionals.set(3);
      }
      if (struct.isSetOpNumber()) {
        optionals.set(4);
      }
      if (struct.isSetCommitNumber()) {
        optionals.set(5);
      }
      if (struct.isSetReplicaNumber()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetViewNumber()) {
        oprot.writeI32(struct.viewNumber);
      }
      if (struct.isSetLogs()) {
        {
          oprot.writeI32(struct.logs.size());
          for (Map.Entry<Integer, Log> _iter33 : struct.logs.entrySet())
          {
            oprot.writeI32(_iter33.getKey());
            _iter33.getValue().write(oprot);
          }
        }
      }
      if (struct.isSetNonce()) {
        oprot.writeByte(struct.nonce);
      }
      if (struct.isSetCheckPoint()) {
        oprot.writeI32(struct.checkPoint);
      }
      if (struct.isSetOpNumber()) {
        oprot.writeI32(struct.opNumber);
      }
      if (struct.isSetCommitNumber()) {
        oprot.writeI32(struct.commitNumber);
      }
      if (struct.isSetReplicaNumber()) {
        oprot.writeI32(struct.replicaNumber);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecoveryResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.viewNumber = iprot.readI32();
        struct.setViewNumberIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map34 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.logs = new HashMap<Integer,Log>(2*_map34.size);
          int _key35;
          Log _val36;
          for (int _i37 = 0; _i37 < _map34.size; ++_i37)
          {
            _key35 = iprot.readI32();
            _val36 = new Log();
            _val36.read(iprot);
            struct.logs.put(_key35, _val36);
          }
        }
        struct.setLogsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.nonce = iprot.readByte();
        struct.setNonceIsSet(true);
      }
      if (incoming.get(3)) {
        struct.checkPoint = iprot.readI32();
        struct.setCheckPointIsSet(true);
      }
      if (incoming.get(4)) {
        struct.opNumber = iprot.readI32();
        struct.setOpNumberIsSet(true);
      }
      if (incoming.get(5)) {
        struct.commitNumber = iprot.readI32();
        struct.setCommitNumberIsSet(true);
      }
      if (incoming.get(6)) {
        struct.replicaNumber = iprot.readI32();
        struct.setReplicaNumberIsSet(true);
      }
    }
  }

}

