/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ReplicaStatus implements org.apache.thrift.TEnum {
  normal(0),
  view_change(1),
  recovering(2);

  private final int value;

  private ReplicaStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReplicaStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return normal;
      case 1:
        return view_change;
      case 2:
        return recovering;
      default:
        return null;
    }
  }
}
