/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-11")
public class RequestFailure implements org.apache.thrift.TBase<RequestFailure, RequestFailure._Fields>, java.io.Serializable, Cloneable, Comparable<RequestFailure> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RequestFailure");

  private static final org.apache.thrift.protocol.TField REQUEST_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("requestNumber", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField RESPONSE_STRING_FIELD_DESC = new org.apache.thrift.protocol.TField("responseString", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RequestFailureStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RequestFailureTupleSchemeFactory());
  }

  public long requestNumber; // required
  public String responseString; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REQUEST_NUMBER((short)1, "requestNumber"),
    RESPONSE_STRING((short)2, "responseString");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REQUEST_NUMBER
          return REQUEST_NUMBER;
        case 2: // RESPONSE_STRING
          return RESPONSE_STRING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REQUESTNUMBER_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REQUEST_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("requestNumber", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64        , "long")));
    tmpMap.put(_Fields.RESPONSE_STRING, new org.apache.thrift.meta_data.FieldMetaData("responseString", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RequestFailure.class, metaDataMap);
  }

  public RequestFailure() {
  }

  public RequestFailure(
    long requestNumber,
    String responseString)
  {
    this();
    this.requestNumber = requestNumber;
    setRequestNumberIsSet(true);
    this.responseString = responseString;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RequestFailure(RequestFailure other) {
    __isset_bitfield = other.__isset_bitfield;
    this.requestNumber = other.requestNumber;
    if (other.isSetResponseString()) {
      this.responseString = other.responseString;
    }
  }

  public RequestFailure deepCopy() {
    return new RequestFailure(this);
  }

  @Override
  public void clear() {
    setRequestNumberIsSet(false);
    this.requestNumber = 0;
    this.responseString = null;
  }

  public long getRequestNumber() {
    return this.requestNumber;
  }

  public RequestFailure setRequestNumber(long requestNumber) {
    this.requestNumber = requestNumber;
    setRequestNumberIsSet(true);
    return this;
  }

  public void unsetRequestNumber() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REQUESTNUMBER_ISSET_ID);
  }

  /** Returns true if field requestNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetRequestNumber() {
    return EncodingUtils.testBit(__isset_bitfield, __REQUESTNUMBER_ISSET_ID);
  }

  public void setRequestNumberIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REQUESTNUMBER_ISSET_ID, value);
  }

  public String getResponseString() {
    return this.responseString;
  }

  public RequestFailure setResponseString(String responseString) {
    this.responseString = responseString;
    return this;
  }

  public void unsetResponseString() {
    this.responseString = null;
  }

  /** Returns true if field responseString is set (has been assigned a value) and false otherwise */
  public boolean isSetResponseString() {
    return this.responseString != null;
  }

  public void setResponseStringIsSet(boolean value) {
    if (!value) {
      this.responseString = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REQUEST_NUMBER:
      if (value == null) {
        unsetRequestNumber();
      } else {
        setRequestNumber((Long)value);
      }
      break;

    case RESPONSE_STRING:
      if (value == null) {
        unsetResponseString();
      } else {
        setResponseString((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REQUEST_NUMBER:
      return Long.valueOf(getRequestNumber());

    case RESPONSE_STRING:
      return getResponseString();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REQUEST_NUMBER:
      return isSetRequestNumber();
    case RESPONSE_STRING:
      return isSetResponseString();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RequestFailure)
      return this.equals((RequestFailure)that);
    return false;
  }

  public boolean equals(RequestFailure that) {
    if (that == null)
      return false;

    boolean this_present_requestNumber = true;
    boolean that_present_requestNumber = true;
    if (this_present_requestNumber || that_present_requestNumber) {
      if (!(this_present_requestNumber && that_present_requestNumber))
        return false;
      if (this.requestNumber != that.requestNumber)
        return false;
    }

    boolean this_present_responseString = true && this.isSetResponseString();
    boolean that_present_responseString = true && that.isSetResponseString();
    if (this_present_responseString || that_present_responseString) {
      if (!(this_present_responseString && that_present_responseString))
        return false;
      if (!this.responseString.equals(that.responseString))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_requestNumber = true;
    list.add(present_requestNumber);
    if (present_requestNumber)
      list.add(requestNumber);

    boolean present_responseString = true && (isSetResponseString());
    list.add(present_responseString);
    if (present_responseString)
      list.add(responseString);

    return list.hashCode();
  }

  @Override
  public int compareTo(RequestFailure other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRequestNumber()).compareTo(other.isSetRequestNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRequestNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.requestNumber, other.requestNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResponseString()).compareTo(other.isSetResponseString());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponseString()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.responseString, other.responseString);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RequestFailure(");
    boolean first = true;

    sb.append("requestNumber:");
    sb.append(this.requestNumber);
    first = false;
    if (!first) sb.append(", ");
    sb.append("responseString:");
    if (this.responseString == null) {
      sb.append("null");
    } else {
      sb.append(this.responseString);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RequestFailureStandardSchemeFactory implements SchemeFactory {
    public RequestFailureStandardScheme getScheme() {
      return new RequestFailureStandardScheme();
    }
  }

  private static class RequestFailureStandardScheme extends StandardScheme<RequestFailure> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RequestFailure struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REQUEST_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.requestNumber = iprot.readI64();
              struct.setRequestNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESPONSE_STRING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.responseString = iprot.readString();
              struct.setResponseStringIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RequestFailure struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(REQUEST_NUMBER_FIELD_DESC);
      oprot.writeI64(struct.requestNumber);
      oprot.writeFieldEnd();
      if (struct.responseString != null) {
        oprot.writeFieldBegin(RESPONSE_STRING_FIELD_DESC);
        oprot.writeString(struct.responseString);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RequestFailureTupleSchemeFactory implements SchemeFactory {
    public RequestFailureTupleScheme getScheme() {
      return new RequestFailureTupleScheme();
    }
  }

  private static class RequestFailureTupleScheme extends TupleScheme<RequestFailure> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RequestFailure struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRequestNumber()) {
        optionals.set(0);
      }
      if (struct.isSetResponseString()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetRequestNumber()) {
        oprot.writeI64(struct.requestNumber);
      }
      if (struct.isSetResponseString()) {
        oprot.writeString(struct.responseString);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RequestFailure struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.requestNumber = iprot.readI64();
        struct.setRequestNumberIsSet(true);
      }
      if (incoming.get(1)) {
        struct.responseString = iprot.readString();
        struct.setResponseStringIsSet(true);
      }
    }
  }

}

