/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class RequestUnion extends org.apache.thrift.TUnion<RequestUnion, RequestUnion._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RequestUnion");
  private static final org.apache.thrift.protocol.TField REQUEST_REDIRECT_FIELD_DESC = new org.apache.thrift.protocol.TField("requestRedirect", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField REQUEST_SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("requestSuccess", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField REQUEST_FAILURE_FIELD_DESC = new org.apache.thrift.protocol.TField("requestFailure", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REQUEST_REDIRECT((short)1, "requestRedirect"),
    REQUEST_SUCCESS((short)2, "requestSuccess"),
    REQUEST_FAILURE((short)3, "requestFailure");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REQUEST_REDIRECT
          return REQUEST_REDIRECT;
        case 2: // REQUEST_SUCCESS
          return REQUEST_SUCCESS;
        case 3: // REQUEST_FAILURE
          return REQUEST_FAILURE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REQUEST_REDIRECT, new org.apache.thrift.meta_data.FieldMetaData("requestRedirect", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RequestRedirect.class)));
    tmpMap.put(_Fields.REQUEST_SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("requestSuccess", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RequestSuccess.class)));
    tmpMap.put(_Fields.REQUEST_FAILURE, new org.apache.thrift.meta_data.FieldMetaData("requestFailure", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RequestFailure.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RequestUnion.class, metaDataMap);
  }

  public RequestUnion() {
    super();
  }

  public RequestUnion(_Fields setField, Object value) {
    super(setField, value);
  }

  public RequestUnion(RequestUnion other) {
    super(other);
  }
  public RequestUnion deepCopy() {
    return new RequestUnion(this);
  }

  public static RequestUnion requestRedirect(RequestRedirect value) {
    RequestUnion x = new RequestUnion();
    x.setRequestRedirect(value);
    return x;
  }

  public static RequestUnion requestSuccess(RequestSuccess value) {
    RequestUnion x = new RequestUnion();
    x.setRequestSuccess(value);
    return x;
  }

  public static RequestUnion requestFailure(RequestFailure value) {
    RequestUnion x = new RequestUnion();
    x.setRequestFailure(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case REQUEST_REDIRECT:
        if (value instanceof RequestRedirect) {
          break;
        }
        throw new ClassCastException("Was expecting value of type RequestRedirect for field 'requestRedirect', but got " + value.getClass().getSimpleName());
      case REQUEST_SUCCESS:
        if (value instanceof RequestSuccess) {
          break;
        }
        throw new ClassCastException("Was expecting value of type RequestSuccess for field 'requestSuccess', but got " + value.getClass().getSimpleName());
      case REQUEST_FAILURE:
        if (value instanceof RequestFailure) {
          break;
        }
        throw new ClassCastException("Was expecting value of type RequestFailure for field 'requestFailure', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case REQUEST_REDIRECT:
          if (field.type == REQUEST_REDIRECT_FIELD_DESC.type) {
            RequestRedirect requestRedirect;
            requestRedirect = new RequestRedirect();
            requestRedirect.read(iprot);
            return requestRedirect;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case REQUEST_SUCCESS:
          if (field.type == REQUEST_SUCCESS_FIELD_DESC.type) {
            RequestSuccess requestSuccess;
            requestSuccess = new RequestSuccess();
            requestSuccess.read(iprot);
            return requestSuccess;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case REQUEST_FAILURE:
          if (field.type == REQUEST_FAILURE_FIELD_DESC.type) {
            RequestFailure requestFailure;
            requestFailure = new RequestFailure();
            requestFailure.read(iprot);
            return requestFailure;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case REQUEST_REDIRECT:
        RequestRedirect requestRedirect = (RequestRedirect)value_;
        requestRedirect.write(oprot);
        return;
      case REQUEST_SUCCESS:
        RequestSuccess requestSuccess = (RequestSuccess)value_;
        requestSuccess.write(oprot);
        return;
      case REQUEST_FAILURE:
        RequestFailure requestFailure = (RequestFailure)value_;
        requestFailure.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case REQUEST_REDIRECT:
          RequestRedirect requestRedirect;
          requestRedirect = new RequestRedirect();
          requestRedirect.read(iprot);
          return requestRedirect;
        case REQUEST_SUCCESS:
          RequestSuccess requestSuccess;
          requestSuccess = new RequestSuccess();
          requestSuccess.read(iprot);
          return requestSuccess;
        case REQUEST_FAILURE:
          RequestFailure requestFailure;
          requestFailure = new RequestFailure();
          requestFailure.read(iprot);
          return requestFailure;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case REQUEST_REDIRECT:
        RequestRedirect requestRedirect = (RequestRedirect)value_;
        requestRedirect.write(oprot);
        return;
      case REQUEST_SUCCESS:
        RequestSuccess requestSuccess = (RequestSuccess)value_;
        requestSuccess.write(oprot);
        return;
      case REQUEST_FAILURE:
        RequestFailure requestFailure = (RequestFailure)value_;
        requestFailure.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case REQUEST_REDIRECT:
        return REQUEST_REDIRECT_FIELD_DESC;
      case REQUEST_SUCCESS:
        return REQUEST_SUCCESS_FIELD_DESC;
      case REQUEST_FAILURE:
        return REQUEST_FAILURE_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public RequestRedirect getRequestRedirect() {
    if (getSetField() == _Fields.REQUEST_REDIRECT) {
      return (RequestRedirect)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'requestRedirect' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setRequestRedirect(RequestRedirect value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.REQUEST_REDIRECT;
    value_ = value;
  }

  public RequestSuccess getRequestSuccess() {
    if (getSetField() == _Fields.REQUEST_SUCCESS) {
      return (RequestSuccess)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'requestSuccess' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setRequestSuccess(RequestSuccess value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.REQUEST_SUCCESS;
    value_ = value;
  }

  public RequestFailure getRequestFailure() {
    if (getSetField() == _Fields.REQUEST_FAILURE) {
      return (RequestFailure)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'requestFailure' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setRequestFailure(RequestFailure value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.REQUEST_FAILURE;
    value_ = value;
  }

  public boolean isSetRequestRedirect() {
    return setField_ == _Fields.REQUEST_REDIRECT;
  }


  public boolean isSetRequestSuccess() {
    return setField_ == _Fields.REQUEST_SUCCESS;
  }


  public boolean isSetRequestFailure() {
    return setField_ == _Fields.REQUEST_FAILURE;
  }


  public boolean equals(Object other) {
    if (other instanceof RequestUnion) {
      return equals((RequestUnion)other);
    } else {
      return false;
    }
  }

  public boolean equals(RequestUnion other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(RequestUnion other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
