/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RequestResponseCode implements org.apache.thrift.TEnum {
  redirected(0),
  completed(1),
  failed(2);

  private final int value;

  private RequestResponseCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RequestResponseCode findByValue(int value) { 
    switch (value) {
      case 0:
        return redirected;
      case 1:
        return completed;
      case 2:
        return failed;
      default:
        return null;
    }
  }
}
