/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ViewChangePhase implements org.apache.thrift.TEnum {
  startViewChange(0),
  doViewChange(1),
  startView(2);

  private final int value;

  private ViewChangePhase(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ViewChangePhase findByValue(int value) { 
    switch (value) {
      case 0:
        return startViewChange;
      case 1:
        return doViewChange;
      case 2:
        return startView;
      default:
        return null;
    }
  }
}
