/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vr.replica.server.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2014-12-8")
public class RedirectResponse implements org.apache.thrift.TBase<RedirectResponse, RedirectResponse._Fields>, java.io.Serializable, Cloneable, Comparable<RedirectResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RedirectResponse");

  private static final org.apache.thrift.protocol.TField PRIMARY_REPLICA_FIELD_DESC = new org.apache.thrift.protocol.TField("primaryReplica", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RedirectResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RedirectResponseTupleSchemeFactory());
  }

  public int primaryReplica; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRIMARY_REPLICA((short)1, "primaryReplica");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRIMARY_REPLICA
          return PRIMARY_REPLICA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRIMARYREPLICA_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRIMARY_REPLICA, new org.apache.thrift.meta_data.FieldMetaData("primaryReplica", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32        , "int")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RedirectResponse.class, metaDataMap);
  }

  public RedirectResponse() {
  }

  public RedirectResponse(
    int primaryReplica)
  {
    this();
    this.primaryReplica = primaryReplica;
    setPrimaryReplicaIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RedirectResponse(RedirectResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    this.primaryReplica = other.primaryReplica;
  }

  public RedirectResponse deepCopy() {
    return new RedirectResponse(this);
  }

  @Override
  public void clear() {
    setPrimaryReplicaIsSet(false);
    this.primaryReplica = 0;
  }

  public int getPrimaryReplica() {
    return this.primaryReplica;
  }

  public RedirectResponse setPrimaryReplica(int primaryReplica) {
    this.primaryReplica = primaryReplica;
    setPrimaryReplicaIsSet(true);
    return this;
  }

  public void unsetPrimaryReplica() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PRIMARYREPLICA_ISSET_ID);
  }

  /** Returns true if field primaryReplica is set (has been assigned a value) and false otherwise */
  public boolean isSetPrimaryReplica() {
    return EncodingUtils.testBit(__isset_bitfield, __PRIMARYREPLICA_ISSET_ID);
  }

  public void setPrimaryReplicaIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PRIMARYREPLICA_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PRIMARY_REPLICA:
      if (value == null) {
        unsetPrimaryReplica();
      } else {
        setPrimaryReplica((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PRIMARY_REPLICA:
      return Integer.valueOf(getPrimaryReplica());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PRIMARY_REPLICA:
      return isSetPrimaryReplica();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RedirectResponse)
      return this.equals((RedirectResponse)that);
    return false;
  }

  public boolean equals(RedirectResponse that) {
    if (that == null)
      return false;

    boolean this_present_primaryReplica = true;
    boolean that_present_primaryReplica = true;
    if (this_present_primaryReplica || that_present_primaryReplica) {
      if (!(this_present_primaryReplica && that_present_primaryReplica))
        return false;
      if (this.primaryReplica != that.primaryReplica)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_primaryReplica = true;
    list.add(present_primaryReplica);
    if (present_primaryReplica)
      list.add(primaryReplica);

    return list.hashCode();
  }

  @Override
  public int compareTo(RedirectResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPrimaryReplica()).compareTo(other.isSetPrimaryReplica());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrimaryReplica()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.primaryReplica, other.primaryReplica);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RedirectResponse(");
    boolean first = true;

    sb.append("primaryReplica:");
    sb.append(this.primaryReplica);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RedirectResponseStandardSchemeFactory implements SchemeFactory {
    public RedirectResponseStandardScheme getScheme() {
      return new RedirectResponseStandardScheme();
    }
  }

  private static class RedirectResponseStandardScheme extends StandardScheme<RedirectResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RedirectResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRIMARY_REPLICA
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.primaryReplica = iprot.readI32();
              struct.setPrimaryReplicaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RedirectResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PRIMARY_REPLICA_FIELD_DESC);
      oprot.writeI32(struct.primaryReplica);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RedirectResponseTupleSchemeFactory implements SchemeFactory {
    public RedirectResponseTupleScheme getScheme() {
      return new RedirectResponseTupleScheme();
    }
  }

  private static class RedirectResponseTupleScheme extends TupleScheme<RedirectResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RedirectResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPrimaryReplica()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetPrimaryReplica()) {
        oprot.writeI32(struct.primaryReplica);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RedirectResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.primaryReplica = iprot.readI32();
        struct.setPrimaryReplicaIsSet(true);
      }
    }
  }

}

